
export type BlockName = 
	"after_abstract_route" |
	"after_abstract_route_[" |
	"after_close_response" |
	"after_drop_abstract_route" |
	"after_drop_abstract_route_[" |
	"after_drop_step_[" |
	"after_extracted" |
	"after_extracted_step_[" |
	"after_extracted_step_[_[" |
	"after_hook_after_send" |
	"after_hook_before_parsing_body" |
	"after_hook_before_route_execution" |
	"after_hook_before_send" |
	"after_hook_on_construct_request" |
	"after_hook_on_construct_response" |
	"after_hook_on_error" |
	"after_hook_serialize_body" |
	"after_make_floor" |
	"after_step_[" |
	"after_write_head" |
	"before_abstract_route" |
	"before_abstract_route_[" |
	"before_close_response" |
	"before_extracted" |
	"before_extracted_step_[" |
	"before_extracted_step_[_[" |
	"before_handler" |
	"before_hook_after_send" |
	"before_hook_before_parsing_body" |
	"before_hook_before_route_execution" |
	"before_hook_before_send" |
	"before_hook_on_construct_request" |
	"before_hook_on_construct_response" |
	"before_hook_on_error" |
	"before_hook_serialize_body" |
	"before_no_respose_sent" |
	"before_return" |
	"before_skip_step_[" |
	"before_step_[" |
	"before_write_head" |
	"first_line" |
	"first_line_extracted_catch" |
	"first_line_extracted_try" |
	"first_line_first_catch" |
	"first_line_first_try" |
	"first_line_second_catch" |
	"first_line_second_try" |
	"last_line" |
	"last_line_extracted_catch" |
	"last_line_extracted_try" |
	"last_line_first_catch" |
	"last_line_first_try" |
	"last_line_second_catch" |
	"last_line_second_try" |
	`after_abstract_route_[${string}]` |
	`after_drop_abstract_route_[${string}]` |
	`after_drop_step_[${string}]` |
	`after_extracted_step_[${string}]_[${string}]` |
	`after_extracted_step_[${string}]` |
	`after_step_[${string}]` |
	`before_abstract_route_[${string}]` |
	`before_extracted_step_[${string}]_[${string}]` |
	`before_extracted_step_[${string}]` |
	`before_skip_step_[${string}]` |
	`before_step_[${string}]`;
